### ISSUE TITLE
Restart error in .Net 

### ISSUE THREAD

**Issue by majidnow** [dnp3/opendnp3#350] opened 2020-02-14 09:31 UTC
Hello
I get an error when trying to run the restart command.

I think this error occurs when outstation does not support this command (I just guess) and , although it does not happen in C ++.

https://github.com/dnp3/opendnp3/blob/44c06cb148d40ed150e539895b3fa951376e5f74/dotnet/CLRAdapter/src/CallbackAdapters.cpp#L50

I think this error is related to time converting.

**Comment by emgre** [comment] 2020-02-14 14:20
What error do you get exactly? Can you provide logs showcasing the issue?

I quickly tried it on my machine and couldn't reproduce, but I'm not sure what error you are experiencing, nor what the repro steps are.

**Comment by majidnow** [comment] 2020-02-15 14:33
I using Axon Test 4.3 to simulate outstation for both .Net and C++ master example.
.Net Master Log:
![Capture4](https://user-images.githubusercontent.com/22871148/74589506-2a2aab80-501b-11ea-9d9c-c2fe6e087b88.PNG)

C++ Master Log:
![Capture5](https://user-images.githubusercontent.com/22871148/74589574-a45b3000-501b-11ea-990d-b7e6425c273c.PNG)

Notes:
- The execution of the .Net example stops by an exception on the specified line before.
Exception: timespan overflowed because the duration is too long
- C++ example runs under the same conditions without any fatal error.
- Axon Test use opendnp3 as DNP library too.

**Comment by emgre** [comment] 2020-02-17 17:02
Thanks for the detailed response.

I found the issue and written a bugfix. Have a look at the [`bug/issue-350`](https://github.com/dnp3/opendnp3/tree/bug/issue-350) branch and PR #351. It only affects the 2.x releases.

Can you give it a try and tell me if it fixes your issue?

Thanks!

**Comment by majidnow** [comment] 2020-02-17 17:44
It fixed.

Thanks!

**Comment by emgre** [comment] 2020-02-17 19:04
Great, the fix was released in [2.3.3](https://github.com/dnp3/opendnp3/releases/tag/2.3.3).

**Closed as completed by emgre** 2020-02-17 19:04 UTC
